kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: 1c
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31000
    hostPort: 80
    # Optional, defaults to "0.0.0.0"
    listenAddress: "0.0.0.0"
    # Optional, defaults to tcp
    protocol: tcp
  extraMounts:
  - hostPath: /data/kind
    containerPath: /data/kind
