kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: 1c
networking:
  apiServerAddress: "10.121.1.214"
  apiServerPort: 6443
  kubeProxyMode: "ipvs"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    apiServer:
      certSANs:
      - "10.121.1.214"  # 你的服务器IP地址
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30443
    hostPort: 8443
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30880
    hostPort: 8080
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30881
    hostPort: 8081
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30882
    hostPort: 8082
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30900
    hostPort: 9000
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30942
    hostPort: 9042
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 30943
    hostPort: 9142
    listenAddress: "0.0.0.0"
    protocol: tcp
  extraMounts:
  - hostPath: /etc/localtime
    containerPath: /etc/localtime
  - hostPath: /data/kind
    containerPath: /data/kind
