kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# Optional, defaults "kind".
name: 1c2w
#networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  #apiServerAddress: "127.0.0.1"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  #apiServerPort: 6443
  # Optional, default "iptables" is used
  #kubeProxyMode: "ipvs"
# One control plane node and two "workers".
nodes:
- role: control-plane
  # port forward 80 on the host to 80 on this node
  extraPortMappings:
  - containerPort: 31000
    hostPort: 80
    # Optional, defaults to "0.0.0.0"
    listenAddress: "0.0.0.0"
    # Optional, defaults to tcp
    protocol: tcp
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: /data/kind
    containerPath: /data/kind
    # Optional, default false
    #readOnly: true
- role: worker
- role: worker